import type { NextPage } from 'next'
import Head from 'next/head'
import { useContext } from 'react'
import { MainContext } from '../context'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  const { arweave, warp } = useContext(MainContext)
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className="text-3xl text-green-300 font-bold">
          Hello world!
        </h1>
      </main>
    </div>
  )
}

export default Home
